language: java
before_install:
  - cd contextproject-ms3
  - git clone https://github.com/JorenSix/TarsosDSP
  - cd TarsosDSP/build
  - ant tarsos_dsp_library
  - cd ../../
  - mvn install:install-file -DgroupId=be.tarsosdsp -DartifactId=tarsosdsp -Dpackaging=jar -Dversion=2.2 -Dfile=TarsosDSP/build/TarsosDSP-2.2.jar -DgeneratePom=true
notifications:
  webhooks:
    - http://octopull.rmhartog.me/api/travis/webhook
after_script:
  - echo "== CHECKSTYLE_RESULT ==" && cat "target/checkstyle-result.xml" && echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT ==" && cat "target/pmd.xml" && echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT ==" && cat "target/findbugsXml.xml" && echo "== END_FINDBUGS_RESULT =="
script: mvn site -B
